# Generated by Django 4.1.7 on 2023-03-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Company', models.TextField(max_length=500, null=True)),
                ('Location', models.TextField(max_length=500, null=True)),
                ('JD', models.TextField(max_length=20000, null=True)),
                ('posted', models.TextField(max_length=500, null=True)),
                ('link', models.TextField(max_length=10000, null=True)),
            ],
        ),
    ]
